class I18n {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'home': 'Home',
      'favorites': 'Favorites',
      'keymapper': 'Keymapper',
      'files': 'Files',
      'monitor': 'Monitor',
      'app_drawer': 'App Drawer',
      'scripts': 'Scripts',
      'shortcuts': 'Shortcuts',
      'settings': 'Settings',
      'command': 'Command',
      'select_device': 'Select Device',
      'webcam_mode': '📷 WEBCAM MODE',
      'connected': 'Connected',
      'copy_cmd': 'Command copied to clipboard',
      'save_preset': 'Save Current Settings as Preset',
      'launch_all': 'Launch All',
      'launch': 'Launch ▶',
      'stop': 'Stop ⏹',
      'apply': 'Apply',
      'delete': 'Delete',
      'active': 'ACTIVE',
      'applications': 'Applications',
      'search_app': 'Search App...',
      'general': 'General & Video Source',
      'video_source': 'Video Source:',
      'screen_mirror': '📱 Screen Mirroring',
      'camera_webcam': '📷 Camera (PC Webcam)',
      'camera_facing': 'Camera Facing',
      'back_camera': 'Back Camera (Main)',
      'front_camera': 'Front Camera (Selfie)',
      'window_title': 'Window Title',
      'fullscreen': 'Fullscreen',
      'screen_off': 'Screen off',
      'stay_awake': 'Stay Awake',
      'borderless': 'Window Borderless',
      'always_on_top': 'Window Always on Top',
      'disable_screensaver': 'Disable Screensaver',
      'video_bitrate': 'Video Bit Rate',
      'max_fps': 'Max FPS',
      'max_size': 'Max Size',
      'audio': 'Audio',
      'audio_bitrate': 'Audio Bit Rate',
      'audio_buffer': 'Audio Buffer (ms)',
      'audio_codec': 'Audio Codec Options',
      'audio_source': 'Audio Source',
      'no_audio': 'No Audio',
      'audio_duplication': 'Audio Duplication',
      'virtual_display': 'Virtual Display',
      'new_display': 'New Display',
      'resolution': 'Resolution',
      'recording': 'Recording',
      'record_screen': 'Record Screen',
      'record_audio_only': 'Record Audio Only',
      'check_updates': 'Check for Updates',
      'auto_download_btn': '📥 1-Click Auto-Download Scrcpy v4.1',
      'downloading': 'Downloading...',
      'ready': 'Ready',
      'missing': 'Missing',
      'test_availability': 'Test Availability',
      'language': 'Language / Язык',
      'preset_name': 'Preset Name',
      'description': 'Description',
      'cancel': 'Cancel',
      'save': 'Save',
      'theme_customizer': '🎨 Appearance & Theme Customization',
      'accent_color': 'Accent Color',
      'oled_mode': 'OLED Pure Black Mode',
      'window_snap': '🪟 Quick Window Snap & Positioning',
      'snap_right': 'Snap Right',
      'snap_left': 'Snap Left',
      'snap_pip': 'Compact PiP',
      'snap_center': 'Center',
      'file_explorer': '📂 Android File Explorer (/sdcard)',
      'upload_file': 'Upload to Phone',
      'download_file': 'Download to PC',
      'performance_monitor': '📊 Real-time Device Diagnostics',
      'keymapper_title': '🎮 Visual Gamepad & Keymapper',
    },
    'ru': {
      'home': 'Главная',
      'favorites': 'Избранное',
      'keymapper': 'Кеймаппер',
      'files': 'Файлы',
      'monitor': 'Монитор',
      'app_drawer': 'Приложения',
      'scripts': 'Скрипты',
      'shortcuts': 'Горячие клавиши',
      'settings': 'Настройки',
      'command': 'Команда Scrcpy',
      'select_device': 'Выберите устройство',
      'webcam_mode': '📷 РЕЖИМ ВЕБ-КАМЕРЫ',
      'connected': 'Подключено',
      'copy_cmd': 'Команда скопирована в буфер обмена',
      'save_preset': 'Сохранить текущие настройки в пресет',
      'launch_all': 'Запустить все',
      'launch': 'Запустить ▶',
      'stop': 'Стоп ⏹',
      'apply': 'Применить',
      'delete': 'Удалить',
      'active': 'АКТИВЕН',
      'applications': 'Приложения телефона',
      'search_app': 'Поиск приложения...',
      'general': 'Основные настройки и видео',
      'video_source': 'Источник видео:',
      'screen_mirror': '📱 Экран телефона',
      'camera_webcam': '📷 Камера (Веб-камера ПК)',
      'camera_facing': 'Выбор камеры',
      'back_camera': 'Основная камера (Back)',
      'front_camera': 'Фронтальная камера (Selfie)',
      'window_title': 'Заголовок окна',
      'fullscreen': 'Во весь экран',
      'screen_off': 'Выключить экран телефона',
      'stay_awake': 'Не давать уснуть',
      'borderless': 'Окно без рамок',
      'always_on_top': 'Поверх всех окон',
      'disable_screensaver': 'Отключить скринсейвер',
      'video_bitrate': 'Битрейт видео',
      'max_fps': 'Макс. кадров/сек (FPS)',
      'max_size': 'Разрешение (Max Size)',
      'audio': 'Трансляция звука',
      'audio_bitrate': 'Битрейт звука',
      'audio_buffer': 'Буфер звука (мс)',
      'audio_codec': 'Аудиокодек',
      'audio_source': 'Источник аудио',
      'no_audio': 'Без звука',
      'audio_duplication': 'Дублировать звук на ПК',
      'virtual_display': 'Виртуальный дисплей',
      'new_display': 'Новый экран',
      'resolution': 'Разрешение экрана',
      'recording': 'Запись экрана',
      'record_screen': 'Записывать экран',
      'record_audio_only': 'Только запись звука',
      'check_updates': 'Проверить обновления',
      'auto_download_btn': '📥 Скачать Scrcpy v4.1 в 1 клик',
      'downloading': 'Загрузка...',
      'ready': 'Готово',
      'missing': 'Не найдено',
      'test_availability': 'Проверить статус',
      'language': 'Язык / Language',
      'preset_name': 'Название пресета',
      'description': 'Описание',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'theme_customizer': '🎨 Кастомизация темы и акцентов',
      'accent_color': 'Акцентный цвет',
      'oled_mode': 'Режим глубокого черного (OLED Black)',
      'window_snap': '🪟 Быстрое позиционирование окна',
      'snap_right': 'Справа (50%)',
      'snap_left': 'Слева (50%)',
      'snap_pip': 'Мини PiP',
      'snap_center': 'По центру',
      'file_explorer': '📂 Файловый менеджер Android (/sdcard)',
      'upload_file': 'Загрузить на телефон',
      'download_file': 'Скачать на ПК',
      'performance_monitor': '📊 Мониторинг производительности устройства',
      'keymapper_title': '🎮 Визуальный Кеймаппер для игр',
    },
  };

  static String t(String key, [String lang = 'ru']) {
    final map = _strings[lang] ?? _strings['en']!;
    return map[key] ?? key;
  }
}
